---
title: "03_otu_abundance"
---


```{r}
set.seed(0)
require(data.table)
library(dplyr)
#import data 
recalls.use <- data.table::fread('../../data/00/wweia_qc_crp.txt', sep = '\t', header=T)
colnames(recalls.use)

kcal = recalls.use %>% group_by(SEQN) %>% summarise(kcal = sum(Energy))

#hist(kcal$kcal)

recalls.use <- left_join(recalls.use, kcal, by = 'SEQN')

#recall_adjusted <- recalls.use %>% group_by(SEQN) %>% summarise(across(`Capric acid`:Zinc, #list(~./kcal*1000), .names = "{.col}_adjust"))

recall_adjusted <- recalls.use %>% group_by(SEQN) %>% mutate(ingred_g_adjust = Ingred_consumed_g/kcal*1000, water_adjust = Water/kcal*1000)
 

recall_adjusted$ingred_dry_wt = recall_adjusted$ingred_g_adjust - recall_adjusted$water_adjust # get dry weights for ingredients consumed

no_salt_water <- recall_adjusted %>% select(SEQN, ingred_code, ingred_dry_wt) %>% filter(!ingred_code %in% c(2047, 14411, 14429, 14555))

taxa = read.csv("../../data/02/wweia_ingredient_taxa.txt", sep="\t")
colnames(taxa)[3] = 'ingred_code'

no_salt_water_taxa <- merge(no_salt_water, taxa, by = "ingred_code")

write.csv(no_salt_water_taxa, '../../data/03/ingred_tree_compare.csv')

length(unique(no_salt_water_taxa$SEQN))
```


```{r}
# sum total grams of each food eaten per subject
otu.total <- aggregate(ingred_dry_wt ~ SEQN + FoodID, data=no_salt_water_taxa, FUN="sum")
colnames(otu.total)<-c("UserName", "FoodCode", "FoodAmt") #rename columns for creating otu_table
write.table(otu.total, "../../data/03/recalls_e_adjust_drywt_no_salt_water.txt", sep="\t", row.names=F, quote=F)
```

```{r}
#sanity check-- how many unique taxa are in here? 
length(unique(no_salt_water_taxa$FoodID)) 
length(unique(otu.total$FoodCode)) 
```

```{r}
#Need to merge the ingredient codes with the wweia_ingredient_taxonomy
taxonomy = read.csv("../../data/02/wweia_ingredient_taxonomy.txt", sep="\t") 
taxonomy$taxonomy <- gsub(pattern = ";", replacement = "\\|", x = taxonomy$taxonomy)
write.table(taxonomy, "../../data/02/wweia_ingredient_taxonomy_pipe_delim.txt", sep="\t", row.names=F, quote=F)
```


```{r}
source("../../lib/make.food.otu_2.R")
```


```{r}
make.food.otu(food_records_fn = "../../data/03/recalls_e_adjust_drywt_no_salt_water.txt",
              food_record_id = "UserName", 
              food_taxonomy_fn= "../../data/02/wweia_ingredient_taxonomy_pipe_delim.txt", 
              output_fn="../../data/03/ingred_otu_e_adjust_drywt_no_salt_water.txt")
```
